services:
  eventswebapplication:
    image: ${DOCKER_REGISTRY-}eventswebapplication
    build:
      context: .
      dockerfile: EventsWebApplication/Dockerfile
    ports:
      - "8080:80"
    environment:
        ConnectionStrings_Default: "Host=db;Port=5432;Database=EventApp;Username=postgres;Password=1234"
    depends_on:
      - db
  client:
    image: client
    build:
      context: ../event-app
      dockerfile: Dockerfile
    ports: 
      - "5001:3000"
  proxy:
    image: nginx:alpine
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"
    depends_on:
      - db
      - client
      - eventswebapplication
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: EventApp
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: