services:
  eventswebapplication:
    image: ${DOCKER_REGISTRY-}eventswebapplication
    build:
      context: .
      dockerfile: EventsWebApplication/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  client:
    image: client
    build:
      context: ../event-app
      dockerfile: Dockerfile
    ports: 
      - "5001:3000"


    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eventapp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: